baseURL = "https://example.com"
title = "Eureka Demo"

theme = "eureka"

paginate = 3
copyright = "&copy; 2020 <a href=\"https://www.wangchucheng.com/\">C. Wang</a> and <a href=\"https://www.ruiqima.com/\">R. Ma</a>"
enableGitInfo = false
enableEmoji = true
summaryLength = 75

defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean.
defaultContentLanguageInSubdir = false

# Uncomment for google analytics
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = false
    noClasses = false
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "authors"

[build]
  useResourceCacheWhen = "always"