mainSections = ["posts"]
description = "Eureka is a elegant and powerful theme for Hugo."

repoURL = ""
# If it is a Github repo, leave blank
repoEditURL = ""

dateFormat = ""

titleSeparator = ""

# Options: auto, light and dark. Default is auto.
colorScheme = ""

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType = "Person"
icon = "images/icon.png"
publisherName = "C. Wang"
publisherLogo = ""

[math]
  handler = "katex"

  # [math.katex]
  #   # Browse https://katex.org/docs/options.html to see the options available.
  #   # KaTeX's Auto-render ignores `displayMode` property of the options, so this property will not work.
  #   # You can list the key and value you want as below.
  #   leqno = ""

[comment]
  # Options: disqus and commento.
  platform = ""

  [comment.disqus]
    shortname = ""

  [comment.commento]
    # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty. 
    url = ""